# Generated by Django 5.2.5 on 2025-08-23 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(blank=True, max_length=255, null=True)),
                ('persian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CoinPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='crypto.coin')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
