# Generated by Django 5.2.5 on 2025-08-23 16:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_coin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.CreateModel(
            name='CoinPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='crypto.coin')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
