# Generated by Django 5.2.5 on 2025-08-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_alter_coin_price_coinpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='persian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
